#Spring Data JPA Hibernate Configuration
spring.application.name=Vehix Platform
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.naming.physical-strategy=com.vehix.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy

# Application Information for Documentation

# Elements take their values from maven pom.xml build-related information

# Custom Properties for Documentation
# suppress inspection "SpringBootApplicationProperties"
documentation.application.description=@project.description@
# suppress inspection "SpringBootApplicationProperties"
documentation.application.version=@project.version@

# JWT Configuration Properties

# Custom Properties for JWT
# suppress inspection "SpringBootApplicationProperties"
authorization.jwt.secret = WriteHereYourSecretStringForTokenSigningCredentials
# suppress inspection "SpringBootApplicationProperties"
authorization.jwt.expiration.days = 7